packages:
  - "docs"
  - "lambdas/*"
  - "src/*"
  - "tests/*"
  - "tools/*"
blockExoticSubdeps: true

catalogs:
  app:
    async-wait-until: "^2.0.31"
    aws-embedded-metrics: "^4.2.1"
    cloudevents: "^10.0.0"
    nhsuk-frontend: "^8.1.1"
    p-map: "^4.0.0"
    pino: "^10.3.1"
    table: "^6.9.0"
    yargs: "^17.7.2"
    zod: "^4.3.6"
  aws:
    "@aws-sdk/client-cloudwatch": "^3.1025.0"
    "@aws-sdk/client-cloudwatch-logs": "^3.1023.0"
    "@aws-sdk/client-s3": "^3.1024.0"
    "@aws-sdk/client-sqs": "^3.1023.0"
    "@aws-sdk/client-ssm": "^3.1025.0"
    "@aws-sdk/client-sts": "^3.1023.0"
    "@aws-sdk/credential-providers": "^3.1023.0"
  lint:
    "@eslint/js": "^9.39.4"
    "@stylistic/eslint-plugin": "^5.10.0"
    "@typescript-eslint/parser": "^8.57.2"
    eslint: "^9.39.3"
    eslint-config-airbnb-extended: "^3.1.0"
    eslint-config-prettier: "^10.1.8"
    eslint-import-resolver-typescript: "^4.4.4"
    eslint-plugin-html: "^8.1.4"
    eslint-plugin-import-x: "^4.16.2"
    eslint-plugin-jest: "^29.15.2"
    eslint-plugin-json: "^4.0.1"
    eslint-plugin-jsx-a11y: "^6.10.2"
    eslint-plugin-no-relative-import-paths: "^1.6.1"
    eslint-plugin-prettier: "^5.5.5"
    eslint-plugin-security: "^4.0.0"
    eslint-plugin-sonarjs: "^4.0.2"
    eslint-plugin-sort-destructure-keys: "^3.0.0"
    eslint-plugin-unicorn: "^63.0.0"
    typescript-eslint: "^8.57.2"
  test:
    "@types/jest": "^30.0.0"
    jest: "^30.3.0"
    jest-environment-jsdom: "^30.3.0"
    jest-html-reporter: "^4.4.0"
    jest-mock-extended: "^4.0.0"
    lcov-result-merger: "^5.0.1"
    ts-jest: "^29.4.9"
  tools:
    "@tsconfig/node22": "^22.0.5"
    "@types/aws-lambda": "^8.10.161"
    "@types/node": "^24.12.0"
    "@types/yargs": "^17.0.24"
    esbuild: "^0.28.0"
    ts-node: "^10.9.2"
    tsx: "^4.21.0"
    typescript: "^5.9.3"

engineStrict: true
ignoreDepScripts: true
minimumReleaseAge: 2880
nodeOptions: "${NODE_OPTIONS:- } --experimental-vm-modules"
trustPolicy: no-downgrade
trustPolicyExclude:
  - "semver@6.3.1"
