name: "Acceptance stage"

on:
  workflow_call:
    inputs:
      build_datetime:
        description: "Build datetime, set by the CI/CD pipeline workflow"
        required: true
        type: string
      build_timestamp:
        description: "Build timestamp, set by the CI/CD pipeline workflow"
        required: true
        type: string
      build_epoch:
        description: "Build epoch, set by the CI/CD pipeline workflow"
        required: true
        type: string
      nodejs_version:
        description: "Node.js version, set by the CI/CD pipeline workflow"
        required: true
        type: string
      python_version:
        description: "Python version, set by the CI/CD pipeline workflow"
        required: true
        type: string
      terraform_version:
        description: "Terraform version, set by the CI/CD pipeline workflow"
        required: true
        type: string
      version:
        description: "Version of the software, set by the CI/CD pipeline workflow"
        required: true
        type: string
      target_environment:
        description: "Environment to run acceptance tests with"
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  run-acceptance-tests:
    name: Run Acceptance Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - name: "Use Node.js"
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4        with:
          node-version: "${{ inputs.nodejs_version }}"
          registry-url: "https://npm.pkg.github.com"
          scope: "@nhsdigital"

      - name: Trigger Acceptance Tests
        shell: bash
        env:
          APP_PEM_FILE: ${{ secrets.APP_PEM_FILE }}
          APP_CLIENT_ID: ${{ secrets.APP_CLIENT_ID }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_ENVIRONMENT: ${{ inputs.target_environment }}
        run: |
          .github/scripts/dispatch_internal_repo_workflow.sh \
            --targetWorkflow "dispatch-contextual-tests-dynamic-env.yaml" \
            --infraRepoName "nhs-notify-client-callbacks" \
            --releaseVersion "${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" \
            --overrideProjectName "nhs" \
            --targetEnvironment "$TARGET_ENVIRONMENT" \
            --targetAccountGroup "nhs-notify-client-callbacks-dev" \
            --targetComponent "callbacks"
